import Head from "next/head";
import styled from "styled-components";
import dynamic from "next/dynamic";
////////////////////////////////////////////////////////
//////swiper slider/////////////////
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
//////

const BrandCarousel = dynamic(
  () => import("../src/components/home/Brands/Brands"),
  { ssr: false }
);
const ProductSlider = dynamic(
  () => import("../src/components/home/productsSlider/ProductSlider"),
  { ssr: false }
);
import Banners from "../src/components/home/Banners/Banners";
import Header from "../src/components/Header/Header";
import LandingCarousel from "../src/components/home/LandingCarousel/LandingCarousel";

/////styles
const TopSection = styled.div`
  width: 100%;
  height: 80vh;
  background-color: #df363e;
`;
export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LandingCarousel />
        <BrandCarousel />
        <ProductSlider />
        {/* <Banners1 /> */}
        {/* <Banners1 />
        <Banners2 />
        <Banners3 /> */}
        <Banners />
      </main>
    </div>
  );
}
