export const productsData = [
  {
    img: "/images/home/P-1.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-2.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-3.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-1.png",
    productName: "Mya Silver Hookah gummies",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-2.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-3.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/Product-imgnotfound.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-2.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-3.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/Product-imgnotfound.png",
    productName: "Mya Silver Hookah gummies",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-2.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-3.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/Product-imgnotfound.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-2.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-3.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-1.png",
    productName: "Mya Silver Hookah gummies",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-2.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
  {
    img: "/images/home/P-3.png",
    bgImage: "/images/home/Rectangle-6.png",
    productName: "Mya Silver Hookah",
    title: "Mya bambino gold social",
    standardPrice: 50.993939,
    standardPriceWithoutDiscount: 54.99343,
  },
];
